##### Profil #####
owner:
  name: "Mohammad Miftakhus Sholikin"
  avatar: /pengaturan/biography-photo.jpg
  bio: "Adeg-adeg anteb."
  email: mohammad.miftakhus.sholikin@gmail.com
  github: mohammad-miftakhus-sholikin
  orcid: 0000-0001-8677-6982
  researchgate: Mohammad_Sholikin2
  bing-verify: # username
  codepen: # username
  disqus-shortname: # username
  dribbble: # username
  facebook: # username
  flickr: # username
  foursquare: # username
  google:
    analytics: # username
    plus: # username
    scholar: koSsmk8AAAAJ
    verify: # username
  instagram: # username
  lastfm: # username
  linkedin: mohammad-miftakhus-sholikin
  mendeley: # mohammad.miftakhus.sholikin@gmail.com
  pinterest: # username
  stackoverflow: # 123456/username → ambil dua segmen terakhir dari URL
  steam: # username
  soundcloud: # username
  twitter: # username (tanpa @)
  tumblr: # username
  weibo: # username
  xing: # username
  youtube: # username

##### Konfigurasi Logo #####
title: Sholikin
locale: en_US
logo: /pengaturan/logo-icon.svg

##### Konfigurasi Warna Dasar #####
highlight-color: '#800000ff'
lowlight-color: '#000'

##### Konfigurasi Dasar #####
baseurl: /
url: mohammad-miftakhus-sholikin.github.io/academic_website/

exclude: 
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - LICENSE

highlighter: rouge

markdown: kramdown
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  toc_levels: 1..6

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

##### Lisensi #####
creative-commons:
  cc-by: false
  cc-by-nc: false